version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "automerge"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "@testing-library/*"
      production-dependencies:
        patterns:
          - "react*"
          - "next*"
          - "@clerk/*"
          - "@tanstack/*"
